const employees = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Prepare Sales Report",
        description: "Compile Q2 sales data and summarize in Excel.",
        date: "18 August 2025",
        category: "Reporting",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Client Follow-up Call",
        description: "Follow up with client regarding pending invoice.",
        date: "19 August 2025",
        category: "Client Relations",
        accepted: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Team Meeting",
        description: "Weekly sync-up with sales team.",
        date: "20 August 2025",
        category: "Meetings",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Complete Training Module",
        description: "Finish the assigned training course.",
        date: "30 August 2025",
        category: "Training",
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      completed: 1,
      failed: 0,
      newtask: 1,
      accepted: 2,
    },
    totalTasks: 4,
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Update Website Banner",
        description: "Change promotional banner for upcoming offers.",
        date: "22 August 2025",
        category: "Marketing",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Content Review",
        description: "Review blog drafts before publishing.",
        date: "21 August 2025",
        category: "Content",
        accepted: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Email Campaign",
        description: "Create and schedule mailer for product launch.",
        date: "24 August 2025",
        category: "Marketing",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Market Research",
        description: "Research competitors' pricing models.",
        date: "25 August 2025",
        category: "Research",
        accepted: false,
        newtask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Complete Training Module",
        description: "Finish the assigned training course.",
        date: "30 August 2025",
        category: "Training",
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      completed: 1,
      failed: 1,
      newtask: 1,
      accepted: 2,
    },
    totalTasks: 5,
  },
  {
    id: 3,
    name: "Carol Davis",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Bug Fixing",
        description: "Resolve login authentication bug from QA.",
        date: "18 August 2025",
        category: "Development",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Code Review",
        description: "Review PR #342 for dashboard module.",
        date: "19 August 2025",
        category: "Development",
        accepted: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Write Unit Tests",
        description: "Increase coverage for utils library.",
        date: "23 August 2025",
        category: "Testing",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Create API Documentation",
        description: "Document new inventory APIs for front-end team.",
        date: "21 August 2025",
        category: "Documentation",
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Database Optimization",
        description: "Optimize queries causing high latency.",
        date: "27 August 2025",
        category: "Database",
        accepted: false,
        newtask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Complete Training Module",
        description: "Finish the assigned training course.",
        date: "30 August 2025",
        category: "Training",
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      completed: 1,
      failed: 1,
      newtask: 2,
      accepted: 2,
    },
    totalTasks: 6,
  },
  {
    id: 4,
    name: "David Lee",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Recruitment Drive",
        description: "Schedule interviews for software engineers.",
        date: "20 August 2025",
        category: "HR",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Policy Update",
        description: "Update handbook with remote work guidelines.",
        date: "21 August 2025",
        category: "HR Policy",
        accepted: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Payroll Processing",
        description: "Process August payroll and verify deductions.",
        date: "25 August 2025",
        category: "Finance",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Complete Training Module",
        description: "Finish the assigned training course.",
        date: "30 August 2025",
        category: "Training",
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      completed: 1,
      failed: 0,
      newtask: 1,
      accepted: 2,
    },
    totalTasks: 4,
  },
  {
    id: 5,
    name: "Eva Green",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Inventory Check",
        description: "Verify stock levels in warehouse.",
        date: "19 August 2025",
        category: "Logistics",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Shipment Dispatch",
        description: "Ensure timely dispatch of order #8921.",
        date: "20 August 2025",
        category: "Logistics",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Vendor Meeting",
        description: "Discuss new supply contract terms.",
        date: "21 August 2025",
        category: "Procurement",
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Invoice Verification",
        description: "Cross-check vendor invoices for August.",
        date: "22 August 2025",
        category: "Finance",
        accepted: false,
        newtask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Transport Coordination",
        description: "Arrange transport for bulk delivery.",
        date: "24 August 2025",
        category: "Logistics",
        accepted: true,
        newtask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Complete Training Module",
        description: "Finish the assigned training course.",
        date: "30 August 2025",
        category: "Training",
        accepted: false,
        newtask: true,
        completed: false,
        failed: false,
      },
    ],
    taskCount: {
      completed: 1,
      failed: 0,
      newtask: 2,
      accepted: 3,
    },
    totalTasks: 6,
  },
];

const admin = [
  {
    id: 1,
    name: "Admin User",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees_data = JSON.parse(localStorage.getItem("employees"));
  const admin_data = JSON.parse(localStorage.getItem("admin"));
  return { employees: employees_data, admin: admin_data };
};
